- name: Устанавливает Remmina
  gather_facts: false
  hosts: '{{ playbook_hosts }}'
  become: true
  tasks:
    - name: Include task
      ansible.builtin.include_tasks:
        file: /srv/Data/Ansible/roles/install_standard_soft/tasks/remmina.yml
