- name: Устанавливает Р7 Офис + лицензию
  gather_facts: false
  hosts: '{{ playbook_hosts }}'
  become: true
  tasks:
    - name: Include task
      ansible.builtin.include_tasks:
        file: /srv/Data/Ansible/roles/install_standard_soft/tasks/r7-office.yml
  roles:
    - /srv/Data/Ansible/roles/add_r7-office_lic
