- name: Prepare workstation for work like image
  gather_facts: false
  hosts: '{{ playbook_hosts }}'
  become: true
  roles:
    - ../roles/optimize_workstation
    - ../roles/deploy_wine32
#    - ../roles/set_net_groups
    - ../roles/install_net_automount

